version: 1
name: ludo-monarch
services:
  - type: web
    name: ludo-monarch
    env: node
    buildCommand: cd apps/server && npm install && npm run build
    startCommand: node dist/server.js
    envVars:
      - key: PORT
        value: 5000
      - key: CLIENT_URL
        value: https://ludo-monarch.onrender.com
      - key: NODE_ENV
        value: production
    region: oregon